language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy
 - 2.7

# Use container-based infrastructure
sudo: false

install:
 - pip install pyflakes

script:
 # Static analysis
 - pyflakes .

matrix:
  fast_finish: true
